sudo: required
services:
    - docker

before_install:
    - docker build -t bbessick/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bbessick/docker-react npm run test


deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "dockertest"
    env: "Dockertest-env"
    bucket_name: "elasticbeanstalk-us-west-2-159415607981"
    bucket_path: "dockertest"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY